site_name: Mi Página Personal
site_author: Iker-Ortiz
site_url: https://iker-ortiz0225.github.io

theme:
  name: dracula  # Prueba: material, mkdocs, readthedocs

nav:
  - Inicio: index.md
  - Sobre Mí: sobre-mi.md
  - Mis Estudios: mis-estudios.md
  - Experiencia Laboral: experiencia-laboral.md
# - Proyectos: proyectos.md
  - Contacto: contacto.md

repo_url: https://github.com/iker-ortiz0225/iker-ortiz0225.github.io.git


